PERSON = 0  # Persona
BICYCLE = 1  # Bicicletta
CAR = 2  # Automobile
MOTORCYCLE = 3  # Motocicletta
AIRPLANE = 4  # Aereo
BUS = 5  # Autobus
TRAIN = 6  # Treno
TRUCK = 7  # Camion
BOAT = 8  # Barca
TRAFFIC_LIGHT = 9  # Semaforo
FIRE_HYDRANT = 10  # Idrante antincendio
STOP_SIGN = 11  # Segnale di stop
PARKING_METER = 12  # Parcometro
BENCH = 13  # Panchina
BIRD = 14  # Uccello
CAT = 15  # Gatto
DOG = 16  # Cane
HORSE = 17  # Cavallo
SHEEP = 18  # Pecora
COW = 19  # Mucca
ELEPHANT = 20  # Elefante
BEAR = 21  # Orso
ZEBRA = 22  # Zebra
GIRAFFE = 23  # Giraffa
BACKPACK = 24  # Zaino
UMBRELLA = 25  # Ombrello
HANDBAG = 26  # Borsa
TIE = 27  # Cravatta
SUITCASE = 28  # Valigia
FRISBEE = 29  # Frisbee
SKIS = 30  # Sci
SNOWBOARD = 31  # Snowboard
SPORTS_BALL = 32  # Palla sportiva
KITE = 33  # Aquilone
BASEBALL_BAT = 34  # Mazza da baseball
BASEBALL_GLOVE = 35  # Guanto da baseball
SKATEBOARD = 36  # Skateboard
SURFBOARD = 37  # Tavola da surf
TENNIS_RACKET = 38  # Racchetta da tennis
BOTTLE = 39  # Bottiglia
WINE_GLASS = 40  # Calice da vino
CUP = 41  # Tazza
FORK = 42  # Forchetta
KNIFE = 43  # Coltello
SPOON = 44  # Cucchiaio
BOWL = 45  # Ciotola
BANANA = 46  # Banana
APPLE = 47  # Mela
SANDWICH = 48  # Sandwich
ORANGE = 49  # Arancia
BROCCOLI = 50  # Broccoli
CARROT = 51  # Carota
HOT_DOG = 52  # Hot dog
PIZZA = 53  # Pizza
DONUT = 54  # Ciambella
CAKE = 55  # Torta
CHAIR = 56  # Sedia
COUCH = 57  # Divano
POTTED_PLANT = 58  # Pianta in vaso
BED = 59  # Letto
DINING_TABLE = 60  # Tavolo da pranzo
TOILET = 61  # Water
TV = 62  # TV
LAPTOP = 63  # Laptop
MOUSE = 64  # Mouse
REMOTE = 65  # Telecomando
KEYBOARD = 66  # Tastiera
CELL_PHONE = 67  # Cellulare
MICROWAVE = 68  # Forno a microonde
OVEN = 69  # Forno
TOASTER = 70  # Tostapane
SINK = 71  # Lavello
REFRIGERATOR = 72  # Frigorifero
BOOK = 73  # Libro
CLOCK = 74  # Orologio
VASE = 75  # Vaso
SCISSORS = 76  # Forbici
TEDDY_BEAR = 77  # Orsacchiotto
HAIR_DRIER = 78  # Asciugacapelli
TOOTHBRUSH = 79  # Spazzolino da denti
ELECTRIC_SCOOTER = 80 # monopattino, ma solo su modello tuned
